//! C4: how one frame reaches the screen.
//!
//! Two problems, and they are not the same problem. **Getting the pixels there** is answered by
//! shared memory, and it is answered: measured 2026-08-25 in kitty 0.48.2 under tmux next-3.8, a
//! 990x1350 pane, `t=s` did 78 fps with every frame acknowledged against 8 fps for the same picture
//! as base64 down the pty — 9.7x, and the belief that a multiplexer takes shared memory away turned
//! out to be false, because tmux only forwards the escape and kitty is the one that opens the
//! object. **Putting them in the right place** is not answered by that at all, and this module
//! exists mostly for the second half.
//!
//! ## Why the picture used to land crooked
//!
//! A kitty graphics escape places the image at **kitty's** cursor. Under tmux the escape reaches
//! kitty through `DCS tmux;` passthrough, which goes *around* tmux's screen model rather than
//! through it — so kitty's cursor is wherever tmux's last repaint happened to leave it, and it is
//! not where tmux thinks the cursor is. Sending `\x1b[H` from inside the pane moves the cursor tmux
//! owns; the image still lands at the other one. Measured 2026-08-25 with the spike: six lines of
//! startup log above the frame put the frame six lines down and its bottom off the pane, and every
//! repaint of the pane moved it again. Clearing the screen first is a mitigation and not a fix — it
//! works right up until something else repaints.
//!
//! ## Unicode placeholders, which take the cursor out of the question
//!
//! kitty 0.28 added a second way (`U=1`) that splits transmission from placement:
//!
//! 1. The image is **transmitted** and given a *virtual* placement — a prototype with a size in
//!    cells and no position at all. Nothing is drawn.
//! 2. The image is **placed** by printing ordinary text: runs of U+10EEEE, one per cell, carrying
//!    the image id in the cell's foreground colour and the row and column in combining diacritics.
//!
//! Step 2 goes through the *normal text path*. tmux stores those characters in its own screen like
//! any others, moves them when it redraws, and re-emits them where it decides they belong — so the
//! image follows the text, and the position stops depending on a cursor bru does not own. That is
//! the whole argument for the extra machinery below: not speed, which shared memory already settled,
//! but that the frame is where it is supposed to be after the pane is repainted.
//!
//! ## What this module does not do
//!
//! It does not turn CEF's BGRA into the RGB the protocol is told about (`f=24`) — that is the
//! composer's, which also has the popup layer to blend in — and it does not switch synchronised
//! output (mode 2026) on and off around a frame; the session owns the screen and does that. This
//! module takes a finished RGB buffer and a rectangle of cells, and is responsible for exactly the
//! journey between them.

// **Nothing calls this module yet, and it is the whole module rather than a few items.** C4 is the
// presenter; the session (C3) that owns the screen and the composer (C5) that produces the frames
// are being written beside it, and until one of them is wired up every public item here is
// unreachable from `main`. Thirty `#[allow(dead_code)]` attributes, one per item, would say the same
// thing thirty times and would have to be taken off thirty times. This comes off in one line the day
// the first caller lands — and until then `cargo clippy --all-targets -- -D warnings` stays clean,
// which is the point.
#![allow(dead_code)]

use std::collections::VecDeque;
use std::io::Write;

/// The placeholder character itself: one Private Use code point that means "an image cell here".
pub const PLACEHOLDER: char = '\u{10eeee}';

/// The row/column diacritics, in the order that **is** the encoding: the character at index `n`
/// spells the number `n`.
///
/// **Copied from kitty's own `gen/rowcolumn-diacritics.txt` and then checked against a second,
/// independent copy of the same data** — kitty's generated decoder `kitty/rowcolumn-diacritics.c`,
/// which is a `switch` of ranges rather than a list. Expanding those ranges reproduces this array
/// element for element, all 297 of them, with the decoder's return value one greater than the index
/// here (it reserves 0 for "not one of these"). Two sources that were generated by different code
/// from different Unicode versions agreeing exactly is the only check worth having for a table
/// nobody can proofread by eye.
///
/// The list is what you get from Unicode 6.0.0's `UnicodeData.txt` by taking every non-spacing mark
/// of combining class 230 (the ones that sit *above* the base character) and removing the handful
/// that normalisation is liable to fuse into a precomposed character — `0300` and friends, because
/// `0041 0300` is also a way of spelling `À`, and a host application that normalises its output
/// would silently rewrite a row number into a letter.
///
/// 297 entries is also the hard ceiling on the geometry: a placement can be at most 297 rows by 297
/// columns, which no terminal pane this is aimed at comes close to.
const ROWCOLUMN_DIACRITICS: [char; 297] = [
    '\u{305}', '\u{30d}', '\u{30e}', '\u{310}', '\u{312}', '\u{33d}', '\u{33e}', '\u{33f}',
    '\u{346}', '\u{34a}', '\u{34b}', '\u{34c}', '\u{350}', '\u{351}', '\u{352}', '\u{357}',
    '\u{35b}', '\u{363}', '\u{364}', '\u{365}', '\u{366}', '\u{367}', '\u{368}', '\u{369}',
    '\u{36a}', '\u{36b}', '\u{36c}', '\u{36d}', '\u{36e}', '\u{36f}', '\u{483}', '\u{484}',
    '\u{485}', '\u{486}', '\u{487}', '\u{592}', '\u{593}', '\u{594}', '\u{595}', '\u{597}',
    '\u{598}', '\u{599}', '\u{59c}', '\u{59d}', '\u{59e}', '\u{59f}', '\u{5a0}', '\u{5a1}',
    '\u{5a8}', '\u{5a9}', '\u{5ab}', '\u{5ac}', '\u{5af}', '\u{5c4}', '\u{610}', '\u{611}',
    '\u{612}', '\u{613}', '\u{614}', '\u{615}', '\u{616}', '\u{617}', '\u{657}', '\u{658}',
    '\u{659}', '\u{65a}', '\u{65b}', '\u{65d}', '\u{65e}', '\u{6d6}', '\u{6d7}', '\u{6d8}',
    '\u{6d9}', '\u{6da}', '\u{6db}', '\u{6dc}', '\u{6df}', '\u{6e0}', '\u{6e1}', '\u{6e2}',
    '\u{6e4}', '\u{6e7}', '\u{6e8}', '\u{6eb}', '\u{6ec}', '\u{730}', '\u{732}', '\u{733}',
    '\u{735}', '\u{736}', '\u{73a}', '\u{73d}', '\u{73f}', '\u{740}', '\u{741}', '\u{743}',
    '\u{745}', '\u{747}', '\u{749}', '\u{74a}', '\u{7eb}', '\u{7ec}', '\u{7ed}', '\u{7ee}',
    '\u{7ef}', '\u{7f0}', '\u{7f1}', '\u{7f3}', '\u{816}', '\u{817}', '\u{818}', '\u{819}',
    '\u{81b}', '\u{81c}', '\u{81d}', '\u{81e}', '\u{81f}', '\u{820}', '\u{821}', '\u{822}',
    '\u{823}', '\u{825}', '\u{826}', '\u{827}', '\u{829}', '\u{82a}', '\u{82b}', '\u{82c}',
    '\u{82d}', '\u{951}', '\u{953}', '\u{954}', '\u{f82}', '\u{f83}', '\u{f86}', '\u{f87}',
    '\u{135d}', '\u{135e}', '\u{135f}', '\u{17dd}', '\u{193a}', '\u{1a17}', '\u{1a75}', '\u{1a76}',
    '\u{1a77}', '\u{1a78}', '\u{1a79}', '\u{1a7a}', '\u{1a7b}', '\u{1a7c}', '\u{1b6b}', '\u{1b6d}',
    '\u{1b6e}', '\u{1b6f}', '\u{1b70}', '\u{1b71}', '\u{1b72}', '\u{1b73}', '\u{1cd0}', '\u{1cd1}',
    '\u{1cd2}', '\u{1cda}', '\u{1cdb}', '\u{1ce0}', '\u{1dc0}', '\u{1dc1}', '\u{1dc3}', '\u{1dc4}',
    '\u{1dc5}', '\u{1dc6}', '\u{1dc7}', '\u{1dc8}', '\u{1dc9}', '\u{1dcb}', '\u{1dcc}', '\u{1dd1}',
    '\u{1dd2}', '\u{1dd3}', '\u{1dd4}', '\u{1dd5}', '\u{1dd6}', '\u{1dd7}', '\u{1dd8}', '\u{1dd9}',
    '\u{1dda}', '\u{1ddb}', '\u{1ddc}', '\u{1ddd}', '\u{1dde}', '\u{1ddf}', '\u{1de0}', '\u{1de1}',
    '\u{1de2}', '\u{1de3}', '\u{1de4}', '\u{1de5}', '\u{1de6}', '\u{1dfe}', '\u{20d0}', '\u{20d1}',
    '\u{20d4}', '\u{20d5}', '\u{20d6}', '\u{20d7}', '\u{20db}', '\u{20dc}', '\u{20e1}', '\u{20e7}',
    '\u{20e9}', '\u{20f0}', '\u{2cef}', '\u{2cf0}', '\u{2cf1}', '\u{2de0}', '\u{2de1}', '\u{2de2}',
    '\u{2de3}', '\u{2de4}', '\u{2de5}', '\u{2de6}', '\u{2de7}', '\u{2de8}', '\u{2de9}', '\u{2dea}',
    '\u{2deb}', '\u{2dec}', '\u{2ded}', '\u{2dee}', '\u{2def}', '\u{2df0}', '\u{2df1}', '\u{2df2}',
    '\u{2df3}', '\u{2df4}', '\u{2df5}', '\u{2df6}', '\u{2df7}', '\u{2df8}', '\u{2df9}', '\u{2dfa}',
    '\u{2dfb}', '\u{2dfc}', '\u{2dfd}', '\u{2dfe}', '\u{2dff}', '\u{a66f}', '\u{a67c}', '\u{a67d}',
    '\u{a6f0}', '\u{a6f1}', '\u{a8e0}', '\u{a8e1}', '\u{a8e2}', '\u{a8e3}', '\u{a8e4}', '\u{a8e5}',
    '\u{a8e6}', '\u{a8e7}', '\u{a8e8}', '\u{a8e9}', '\u{a8ea}', '\u{a8eb}', '\u{a8ec}', '\u{a8ed}',
    '\u{a8ee}', '\u{a8ef}', '\u{a8f0}', '\u{a8f1}', '\u{aab0}', '\u{aab2}', '\u{aab3}', '\u{aab7}',
    '\u{aab8}', '\u{aabe}', '\u{aabf}', '\u{aac1}', '\u{fe20}', '\u{fe21}', '\u{fe22}', '\u{fe23}',
    '\u{fe24}', '\u{fe25}', '\u{fe26}', '\u{10a0f}', '\u{10a38}', '\u{1d185}', '\u{1d186}', '\u{1d187}',
    '\u{1d188}', '\u{1d189}', '\u{1d1aa}', '\u{1d1ab}', '\u{1d1ac}', '\u{1d1ad}', '\u{1d242}', '\u{1d243}',
    '\u{1d244}',
];

/// The largest row or column number the encoding can spell, plus one. See [`ROWCOLUMN_DIACRITICS`].
pub const MAX_CELLS: usize = ROWCOLUMN_DIACRITICS.len();

/// The diacritic that spells `n`, or `None` when `n` is past the end of the table.
///
/// Returning an option rather than clamping is deliberate: a clamped row number draws the wrong
/// slice of the picture and looks like a rendering bug, where a refusal looks like what it is.
fn diacritic(n: usize) -> Option<char> {
    ROWCOLUMN_DIACRITICS.get(n).copied()
}

/// The number a diacritic spells, or `None` if it is not one of them.
///
/// The inverse exists for the tests — a table this size is only trustworthy if the round trip is
/// checked over the whole of it — and for whatever later needs to read back a placeholder cell.
/// The table is sorted ascending by construction, which the tests also assert, so this is a binary
/// search rather than a scan.
fn diacritic_number(ch: char) -> Option<usize> {
    ROWCOLUMN_DIACRITICS.binary_search(&ch).ok()
}

/// The SGR sequence that carries an image id in a cell's foreground colour.
///
/// **The 256-colour form is preferred and that is a tmux decision, not an aesthetic one.** The id
/// lives in the foreground colour, and tmux only forwards a 24-bit colour unchanged when it believes
/// the terminal underneath has `RGB`/`Tc` — otherwise it quantises it to the nearest palette entry,
/// which does not corrupt a colour so much as it corrupts an *identifier*, and the placeholder then
/// names an image that does not exist. An id that fits in eight bits can be written as a palette
/// index, which tmux passes through by definition. kitty's own documented example does exactly this:
/// `\x1b[38;5;42m` for image id 42.
///
/// Above eight bits there is no choice but true colour, so the caller is expected to keep bru's ids
/// small (see [`IMAGE_ID_VIEW`]). The top byte of a 32-bit id never travels in the colour at all —
/// it is a third diacritic, see [`most_significant_byte_diacritic`].
fn foreground_for_id(id: u32) -> String {
    let low = id & 0x00ff_ffff;
    if low <= 0xff {
        return format!("\x1b[38;5;{low}m");
    }
    let (r, g, b) = ((low >> 16) & 0xff, (low >> 8) & 0xff, low & 0xff);
    format!("\x1b[38;2;{r};{g};{b}m")
}

/// The third diacritic that carries bits 24..32 of the image id, or `None` when they are zero.
///
/// Omitted when zero because that is both shorter and what the protocol defaults to, and because
/// bru has no reason to hand out ids that large.
fn most_significant_byte_diacritic(id: u32) -> Option<char> {
    let msb = (id >> 24) as usize;
    if msb == 0 { None } else { diacritic(msb) }
}

/// Two image ids, distinct and deliberately small.
///
/// Small, because eight bits keeps the id in a palette index and out of tmux's colour quantiser
/// (see [`foreground_for_id`]). Not *tiny*, because kitty's image ids are a namespace shared by
/// everything in that terminal instance — `kitten icat` and every other well-behaved client start
/// counting from the bottom — so bru sits high in the byte where a collision is least likely. There
/// is no way to reserve one; the protocol offers image *numbers* (`I=`) which the terminal answers
/// with an id it chose, and reading that answer is exactly what a presenter that cannot listen
/// must not do. This is a considered guess and is labelled as one.
pub const IMAGE_ID_VIEW: u32 = 0xbe;
/// The image the transport probe hands over, which is never displayed. Its own id so that failing
/// the probe cannot disturb either of the two real images.
pub const IMAGE_ID_PROBE: u32 = 0xbd;

/// Put one pixel in shared memory for the transport probe to offer the terminal.
///
/// `None` when this machine has no usable `/dev/shm` at all — in which case there is nothing to ask
/// about and [`Transport::Base64`] is the answer without a round trip.
pub(crate) fn shm_probe_publish() -> Option<String> {
    let name = format!("/bru-probe-{}", std::process::id());
    shm_publish(&name, &[0u8; 3]).ok().map(|()| name)
}

/// Put arbitrary bytes in shared memory under a caller's name, for the capability table.
pub(crate) fn shm_stash(name: &str, bytes: &[u8]) -> bool {
    shm_publish(name, bytes).is_ok()
}

/// Take the probe's object back. Harmless if the terminal already consumed it.
pub(crate) fn shm_probe_release(name: &str) {
    shm_unlink(name);
}

/// Ask the terminal whether it can read a frame out of shared memory — `a=q` transmits nothing and
/// displays nothing, it only answers.
///
/// **This exists because a frame does not answer.** Real frames carry `q=2`, which asks for silence,
/// so a terminal that cannot read `t=s` refuses every one of them and bru never hears about it: the
/// pane stays black at full speed. `Transport::Base64` used to be reachable only when `shm_publish`
/// failed *locally*, which is a different question from whether the thing drawing the screen can
/// open the object. Measured 2026-08-26 in zellij 0.46.0.
pub(crate) fn shm_query_escape(name: &str, in_tmux: bool) -> String {
    let escape = format!(
        "\x1b_Gi={IMAGE_ID_PROBE},a=q,t=s,f=24,s=1,v=1;{}\x1b\\",
        base64(name.as_bytes())
    );
    passthrough(&escape, in_tmux)
}

/// What the terminal answered: `Some(true)` for `OK`, `Some(false)` for a refusal such as
/// `ENOENT:...`, and `None` when it said nothing about this image at all.
///
/// **Silence is not a refusal.** A terminal that answers nothing has told us nothing, and the
/// transport that has been working since this frontend was written is the better guess than one
/// chosen from an absence.
pub(crate) fn shm_query_answer(bytes: &[u8]) -> Option<bool> {
    let mut at = 0;
    while let Some(start) = bytes[at..].windows(3).position(|w| w == b"\x1b_G") {
        let start = at + start + 3;
        let end = bytes[start..].windows(2).position(|w| w == b"\x1b\\")? + start;
        let body = &bytes[start..end];
        let split = body.iter().position(|&b| b == b';');
        if let Some(split) = split {
            let (keys, payload) = (&body[..split], &body[split + 1..]);
            if keys.windows(2).any(|w| w == b"i=")
                && String::from_utf8_lossy(keys).contains(&format!("i={IMAGE_ID_PROBE}"))
            {
                return Some(payload.starts_with(b"OK"));
            }
        }
        at = end;
    }
    None
}

/// The popup layer (a `<select>` dropdown), which composes over the view. Its own id so the two do
/// not replace each other.
pub const IMAGE_ID_POPUP: u32 = 0xbf;

/// Where a picture goes, in cells, and which image it is.
///
/// `row` and `col` are **1-based screen coordinates**, because that is what `CSI row;col H` takes
/// and this struct exists to be turned into that. `rows` and `cols` are the size of the placeholder
/// rectangle, which is also what the virtual placement is told (`r=`, `c=`) — kitty fits the image
/// into that rectangle preserving aspect ratio, so the two must agree or the picture is letterboxed
/// inside its own cells.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Placement {
    pub image_id: u32,
    /// The placement id (`p=`). **Fixed rather than left to the terminal**, so that re-transmitting
    /// the same image every frame replaces one virtual placement instead of accumulating one per
    /// frame. The placeholder cells do not name it — that would need the underline colour, which is
    /// one more thing to get through tmux for no gain when there is only ever one placement of an
    /// image, and the protocol says an unnamed placement id means "any virtual placement of this
    /// image".
    pub placement_id: u32,
    pub row: u16,
    pub col: u16,
    pub rows: u16,
    pub cols: u16,
}

impl Placement {
    /// A placement filling a rectangle of the screen, with ids that do not collide.
    pub fn new(image_id: u32, row: u16, col: u16, rows: u16, cols: u16) -> Placement {
        Placement { image_id, placement_id: 1, row, col, rows, cols }
    }

    /// Whether the geometry can be spelled at all. See [`ROWCOLUMN_DIACRITICS`].
    pub fn is_encodable(&self) -> bool {
        self.rows >= 1
            && self.cols >= 1
            && usize::from(self.rows) <= MAX_CELLS
            && usize::from(self.cols) <= MAX_CELLS
    }
}

/// How much of each placeholder cell is spelled out.
///
/// The protocol lets a cell inherit row, column and id byte from the cell to its left, so a run can
/// be written as one full cell followed by bare placeholders — a quarter of the bytes.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Style {
    /// Every cell carries its own row and column. **The default, and the reason is the host
    /// application.** Inheritance is resolved by kitty against the cell to the *left in kitty's own
    /// screen*, so it is only sound while that neighbour is still there with its diacritics intact.
    /// tmux repaints damaged spans, not whole lines, and a span that begins in the middle of a run
    /// of bare placeholders would arrive with nothing to inherit from. The saving is bytes in a
    /// write that happens when the layout changes — not per frame — so there is nothing to buy with
    /// the risk.
    Explicit,
    /// One full cell per row and bare placeholders after it, exactly as kitty documents it. Offered
    /// because it is a quarter of the text and some hosts are not tmux; see the warning above.
    Compact,
}

/// One row of placeholder cells: the colour, the cells, and the foreground put back.
///
/// **No newline, ever, and no cursor movement inside the run.** A character written into the last
/// cell of the last line sets the deferred-wrap flag rather than scrolling — but a newline after it
/// scrolls the pane, and a pane that scrolls by one line takes the image with it.
fn placeholder_row(placement: &Placement, row: u16, style: Style) -> Option<String> {
    let row_mark = diacritic(usize::from(row))?;
    let msb = most_significant_byte_diacritic(placement.image_id);
    let mut text = foreground_for_id(placement.image_id);
    for col in 0..placement.cols {
        text.push(PLACEHOLDER);
        match style {
            Style::Explicit => {
                text.push(row_mark);
                text.push(diacritic(usize::from(col))?);
                if let Some(msb) = msb {
                    text.push(msb);
                }
            }
            // kitty's documented short form: the first cell of the line gives the row and lets the
            // column and the id byte default, everything after it inherits both.
            Style::Compact => {
                if col == 0 {
                    text.push(row_mark);
                    if let Some(msb) = msb {
                        text.push(msb);
                    }
                }
            }
        }
    }
    // Foreground only. A full `SGR 0` here would drop whatever the session had set for the text
    // around the picture, and this module does not own that.
    text.push_str("\x1b[39m");
    Some(text)
}

/// The whole placeholder rectangle, each row positioned with `CSI row;col H`.
///
/// **This is the part that must not be wrapped for passthrough.** It is text; tmux is meant to read
/// it, store it and repaint it. Everything in this module that begins `\x1b_G` goes around tmux and
/// everything here goes through it, and confusing the two is how the picture stops following the
/// pane again.
///
/// Returns `None` for a geometry the diacritics cannot spell, which is the same refusal
/// [`Placement::is_encodable`] reports in advance.
fn placeholder_block(placement: &Placement, style: Style) -> Option<String> {
    if !placement.is_encodable() {
        return None;
    }
    // Save and restore the cursor around the whole block, because the caller's is none of our
    // business: DECSC/DECRC, which tmux implements natively and which also carries the SGR state.
    let mut text = String::from("\x1b7");
    for row in 0..placement.rows {
        let line = placement.row.saturating_add(row);
        text.push_str(&format!("\x1b[{line};{}H", placement.col));
        text.push_str(&placeholder_row(placement, row, style)?);
    }
    text.push_str("\x1b8");
    Some(text)
}

/// Wrap a graphics escape so tmux hands it to the terminal underneath instead of eating it.
///
/// The rule is a `DCS tmux;` wrapper with **every `\x1b` in the payload doubled**, terminated with
/// `\x1b\\`. Without `allow-passthrough on` in tmux the wrapper is dropped and nothing at all is
/// drawn — which is indistinguishable from a terminal with no graphics support, so whoever calls
/// this is the one who has to say which it was.
///
/// `in_tmux` is a parameter and not a look at the environment, so this stays a pure function that
/// the tests can drive both ways in one process.
fn passthrough(payload: &str, in_tmux: bool) -> String {
    if !in_tmux {
        return payload.to_string();
    }
    let mut wrapped = String::with_capacity(payload.len() + payload.len() / 8 + 16);
    wrapped.push_str("\x1bPtmux;");
    for ch in payload.chars() {
        if ch == '\x1b' {
            wrapped.push('\x1b');
        }
        wrapped.push(ch);
    }
    wrapped.push_str("\x1b\\");
    wrapped
}

/// The control keys every transmission in this module shares.
///
/// **`q=2` is not an optimisation and it is not optional here.** kitty's levels are 0 (answer), 1
/// (errors only) and 2 (silence). A presenter runs on the UI thread and cannot stop to read a
/// reply — and a reply nobody reads does not evaporate. Measured 2026-08-25: the spike sent frames
/// without `q`, never read the `OK`s, and tmux delivered the backlog **as keystrokes** to whichever
/// pane had focus, typing `Gi=1;OKGi=1;OK…` into a shell two panes away. Whoever cannot read the
/// answer does not get to ask the question. kitty's own documentation for Unicode placeholders says
/// the same thing for its own reason: a response would confuse the host application.
/// How the terminal is told *where* the picture goes.
///
/// **Two mechanisms, because one of them is not universal.** Unicode placeholders were chosen for
/// this module because they take the cursor out of the question entirely — the cells are text the
/// host repaints by itself, which is the whole reason a picture survives a tmux redraw. But a
/// placeholder is only a picture if the thing drawing the screen implements them, and a host that
/// does not will *accept every frame and show none of it*.
///
/// Measured 2026-08-26, in zellij 0.46.0: `--term-probe` reported 206 fps over shared memory with
/// **every frame acknowledged**, and the pane stayed black. The acknowledgement is `OK` for the
/// graphics command — it says the image was received and the shared memory was read, and says
/// nothing at all about anything being drawn. zellij intercepts graphics and re-emits them rather
/// than relaying the escape the way tmux does, and it does not implement placeholder cells.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Place {
    /// `U=1` plus a rectangle of placeholder cells. Survives a host repaint; needs the host to
    /// implement the placeholder protocol.
    Placeholders,
    /// `C=1` with the cursor moved to the rectangle's top-left cell first. Works anywhere the
    /// graphics protocol works at all, because it asks the terminal for nothing but a picture at
    /// the cursor.
    AtCursor,
}

/// Which mechanism this host can be drawn on.
pub fn place_for_host() -> Place {
    let set = |name: &str| std::env::var_os(name).is_some_and(|value| !value.is_empty());
    place_for(set("TMUX"), set("ZELLIJ"))
}

/// [`place_for_host`] as a function of its inputs, so it can be tested.
///
/// **tmux is answered first and cursor placement is not on the table there.** Under tmux the cursor
/// belongs to tmux: the graphics escape goes *around* it through DCS passthrough and arrives at a
/// terminal whose cursor is wherever tmux last left it, so "at the cursor" names a position nobody
/// agrees on. Placeholders exist for exactly that case.
///
/// Everything that is not a named exception keeps placeholders, which is the path this frontend has
/// been running on since it was written. This is a list of hosts known to need the other one, not a
/// guess about hosts in general.
fn place_for(in_tmux: bool, in_zellij: bool) -> Place {
    if in_tmux {
        return Place::Placeholders;
    }
    if in_zellij {
        return Place::AtCursor;
    }
    Place::Placeholders
}

/// Move the cursor to a placement's top-left cell, saving whatever the session had.
///
/// DECSC/DECRC rather than a second absolute move, because the cursor is the session's and this
/// module does not know where it was. See [`placeholder_block`], which brackets itself the same way
/// and for the same reason.
fn at_cursor_prologue(placement: &Placement) -> String {
    format!("\x1b7\x1b[{};{}H", placement.row, placement.col)
}

/// Put the cursor back. The other half of [`at_cursor_prologue`].
const AT_CURSOR_EPILOGUE: &str = "\x1b8";

fn common_keys(placement: &Placement, width: u32, height: u32, place: Place) -> String {
    // `C=1` and `U=1` sit in the same slot and are the whole difference between the two mechanisms:
    // one says "this image belongs to placeholder cells", the other "draw it here and do not move
    // the cursor". Everything after them is the same picture either way.
    let mode = match place {
        Place::Placeholders => "U=1",
        Place::AtCursor => "C=1",
    };
    format!(
        "a=T,{mode},q=2,i={},p={},f=24,s={width},v={height},c={},r={}",
        placement.image_id, placement.placement_id, placement.cols, placement.rows
    )
}

/// Transmit a frame by handing over the *name* of a shared memory object.
///
/// `t=s` means the payload is a POSIX shared memory name rather than pixels; kitty opens it, reads
/// it and unlinks it. The payload of a graphics escape is always base64, the name included. This is
/// the whole frame in about sixty bytes on the wire, which is why it is 9.7x base64 and why nothing
/// in this module compresses anything.
fn shm_escape(
    name: &str,
    placement: &Placement,
    width: u32,
    height: u32,
    place: Place,
) -> String {
    format!(
        "\x1b_G{},t=s;{}\x1b\\",
        common_keys(placement, width, height, place),
        base64(name.as_bytes())
    )
}

/// How many bytes of base64 go in one escape. The protocol's own limit is 4096.
const CHUNK: usize = 4096;

/// The fallback: the pixels themselves, base64, in 4 KB chunks.
///
/// **Kept because "the terminal supports graphics" and "this process can reach the terminal's
/// `/dev/shm`" are different claims** — an ssh session is the obvious case, and `shm_open` failing
/// is a fact discovered at runtime rather than configured. It is 8 fps on a full pane against 78,
/// so it is a way to still work and not a second way to work.
///
/// Only the first chunk carries the geometry; the rest carry `m` and nothing else, which is the
/// shape kitty documents. `q=2` is repeated on every chunk rather than trusted to stick to the
/// command, because the cost of the extra four bytes is four bytes and the cost of being wrong is
/// keystrokes in somebody else's pane.
fn base64_escapes(
    encoded: &str,
    placement: &Placement,
    width: u32,
    height: u32,
    place: Place,
) -> Vec<String> {
    if encoded.is_empty() {
        return Vec::new();
    }
    let mut escapes = Vec::with_capacity(encoded.len().div_ceil(CHUNK));
    let mut sent = 0;
    while sent < encoded.len() {
        let end = (sent + CHUNK).min(encoded.len());
        let more = i32::from(end < encoded.len());
        let keys = if sent == 0 {
            format!("{},m={more}", common_keys(placement, width, height, place))
        } else {
            format!("q=2,m={more}")
        };
        escapes.push(format!("\x1b_G{keys};{}\x1b\\", &encoded[sent..end]));
        sent = end;
    }
    escapes
}

/// Delete an image and free the pixels the terminal is holding for it.
///
/// `d=I` (capital) is "delete by id **and** release the data"; the lower-case form leaves the image
/// stored. Virtual placements can only be deleted by the `i`, `I`, `r`, `R`, `n` and `N` forms —
/// the ones that address an image rather than a place on the screen — because a virtual placement
/// has no place on the screen to address.
///
/// This does not erase the placeholder characters. They are text in the host application's screen
/// and the session is what owns that.
fn delete_escape(image_id: u32) -> String {
    format!("\x1b_Ga=d,d=I,i={image_id},q=2\x1b\\")
}

/// Base64, written here rather than pulled in: the whole of it is one table and three shifts, and a
/// dependency for that would be a dependency for that.
fn base64(bytes: &[u8]) -> String {
    const ALPHABET: &[u8; 64] =
        b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let b = [chunk[0], *chunk.get(1).unwrap_or(&0), *chunk.get(2).unwrap_or(&0)];
        let n = (u32::from(b[0]) << 16) | (u32::from(b[1]) << 8) | u32::from(b[2]);
        out.push(ALPHABET[(n >> 18) as usize & 63] as char);
        out.push(ALPHABET[(n >> 12) as usize & 63] as char);
        out.push(if chunk.len() > 1 { ALPHABET[(n >> 6) as usize & 63] as char } else { '=' });
        out.push(if chunk.len() > 2 { ALPHABET[n as usize & 63] as char } else { '=' });
    }
    out
}

/// How many whole cells a picture of this many pixels covers.
///
/// The cell size is the pane's pixels divided by its cells — there is no escape that reports it
/// directly, and `TIOCGWINSZ` under tmux reports no pixels at all, which is why the pane's numbers
/// arrive from two different places and are passed in here rather than looked up.
///
/// Rounding is **down**, so the placement never claims a cell it cannot fill. The remainder is up to
/// a cell of unpainted pane at the right and bottom edges, which is a thin strip of background; the
/// alternative is a placement one cell too tall, which pushes the pane into scrolling.
fn cells_for(width: u32, height: u32, cell_width: u32, cell_height: u32) -> Option<(u16, u16)> {
    if cell_width == 0 || cell_height == 0 {
        return None;
    }
    let cols = u16::try_from(width / cell_width).ok()?;
    let rows = u16::try_from(height / cell_height).ok()?;
    if rows == 0 || cols == 0 { None } else { Some((rows, cols)) }
}

// --- damage ------------------------------------------------------------------------------------

/// A rectangle of pixels, in the frame's own coordinates. CEF's `on_paint` hands over a list of
/// these; this is the same thing without a dependency on CEF, so the arithmetic below can be tested
/// without a browser.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Rect {
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
}

/// The one rectangle that covers every dirty rectangle CEF reported, clipped to the frame.
///
/// `None` means nothing changed — which is the only use of damage this module actually makes, and
/// it is worth having on its own: a frame that CEF re-delivers unchanged costs a 4 MB copy into
/// `/dev/shm` and a texture upload for no visible difference.
///
/// ## Why the region is not transmitted, only measured
///
/// The obvious next step — send just the changed pixels — is **not available for a plain image**.
/// Checked against kitty's control-data reference on 2026-08-25: `x`, `y`, `w` and `h` are listed
/// under *keys for image display* and under *keys for animation frame loading*, and under neither
/// heading do they mean "patch the stored pixels of image `i`". For display they select which part
/// of an already-stored image to show; the only way to overwrite a sub-rectangle of stored pixels is
/// the animation path (`a=f` with `x`, `y` and `X=1` for a plain overwrite), which brings frame
/// numbers, inter-frame gaps and an animation state machine along with it. The task description this
/// module was written from assumed `a=t` could do it. It cannot.
///
/// And the reason not to reach for the animation path anyway is the measurement: with `t=s` a full
/// 990x1350 frame is a `memcpy` plus a sixty-byte escape and lands 78 times a second, confirmed.
/// Partial updates would trade that for per-region shared memory objects and a state machine, to
/// save a copy that is not what limits anything. If the transport ever *does* become the limit — a
/// much larger pane, or a terminal without shared memory where every frame is 5 MB of base64 — this
/// is the function that already knows how much of the frame is worth sending, and the second half is
/// then worth writing. Until then it decides whether to send at all.
fn damage_bounds(rects: &[Rect], width: u32, height: u32) -> Option<Rect> {
    let (frame_width, frame_height) = (i32::try_from(width).ok()?, i32::try_from(height).ok()?);
    let mut bounds: Option<(i32, i32, i32, i32)> = None;
    for rect in rects {
        // Clip first. A dirty rectangle that reaches past the frame is not a reason to compute a
        // bounding box that does the same.
        let left = rect.x.max(0);
        let top = rect.y.max(0);
        let right = rect.x.saturating_add(rect.width).min(frame_width);
        let bottom = rect.y.saturating_add(rect.height).min(frame_height);
        if right <= left || bottom <= top {
            continue;
        }
        bounds = Some(match bounds {
            None => (left, top, right, bottom),
            Some((l, t, r, b)) => (l.min(left), t.min(top), r.max(right), b.max(bottom)),
        });
    }
    let (left, top, right, bottom) = bounds?;
    Some(Rect { x: left, y: top, width: right - left, height: bottom - top })
}

// --- shared memory -----------------------------------------------------------------------------

/// How many handed-over shared memory objects are kept before their names are taken back.
///
/// **Not one, and the difference is a race.** kitty unlinks an object once it has read it, so the
/// tidy thing is to unlink the previous frame's when the next one is sent. But `shm_unlink` at the
/// moment kitty has not opened it yet turns that frame into an `ENOENT` and a dropped picture, and
/// at 78 fps the next frame is 13 ms away. Holding three generations gives the terminal about 38 ms
/// of grace and costs three frames of `/dev/shm` — 12 MB at a full pane, against a default
/// `/dev/shm` of half of RAM. Unlinking a name that is already gone fails harmlessly, which is why
/// the tidy-up is unconditional and unchecked.
const RETAINED_FRAMES: usize = 3;

/// Put `bytes` in a fresh POSIX shared memory object under `name`.
///
/// The object is created with `O_EXCL`, so this either makes a new one or fails; it never writes
/// into somebody else's. Everything it opens it closes, on every path, including the failing ones —
/// a leaked descriptor per frame is a file descriptor limit reached in under a minute.
fn shm_publish(name: &str, bytes: &[u8]) -> std::io::Result<()> {
    let c_name = std::ffi::CString::new(name)
        .map_err(|_| std::io::Error::new(std::io::ErrorKind::InvalidInput, "NUL in a shm name"))?;
    // SAFETY: `c_name` is a valid NUL-terminated string that outlives the call, and the flags are
    // the create-or-fail pair, so no existing object can be opened by accident.
    let fd = unsafe {
        libc::shm_open(c_name.as_ptr(), libc::O_CREAT | libc::O_EXCL | libc::O_RDWR, 0o600)
    };
    if fd < 0 {
        return Err(std::io::Error::last_os_error());
    }
    // From here on every exit closes the descriptor, and every *failing* exit also unlinks the
    // object — a name left behind after a failure is megabytes nobody will ever collect.
    let fail = |error: std::io::Error| -> std::io::Result<()> {
        // SAFETY: `fd` came from the `shm_open` above and is closed exactly once, on this path or
        // the successful one; the name is this process's own.
        unsafe {
            libc::close(fd);
            libc::shm_unlink(c_name.as_ptr());
        }
        Err(error)
    };
    let length = match libc::off_t::try_from(bytes.len()) {
        Ok(length) => length,
        Err(_) => {
            return fail(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                "a frame too large to size a shared memory object with",
            ));
        }
    };
    // SAFETY: `fd` is a shared memory object this function just created and owns exclusively.
    if unsafe { libc::ftruncate(fd, length) } != 0 {
        return fail(std::io::Error::last_os_error());
    }
    // SAFETY: the object was just sized to `bytes.len()`, so a mapping of that length lies within
    // it; `MAP_SHARED` is what makes the pixels visible to the terminal that opens the same name.
    let mapped = unsafe {
        libc::mmap(
            std::ptr::null_mut(),
            bytes.len(),
            libc::PROT_READ | libc::PROT_WRITE,
            libc::MAP_SHARED,
            fd,
            0,
        )
    };
    if mapped == libc::MAP_FAILED {
        return fail(std::io::Error::last_os_error());
    }
    // SAFETY: `mapped` is a writable mapping of exactly `bytes.len()` bytes, and the two regions
    // cannot overlap — one is a file mapping the kernel just handed out, the other this process's
    // own heap. The unmap that follows uses the same pointer and the same length.
    unsafe {
        std::ptr::copy_nonoverlapping(bytes.as_ptr(), mapped.cast::<u8>(), bytes.len());
        libc::munmap(mapped, bytes.len());
        libc::close(fd);
    }
    Ok(())
}

/// Take back a shared memory name the terminal did not.
///
/// Unchecked on purpose: the expected outcome is `ENOENT`, because kitty unlinks what it reads, and
/// the whole point of calling this is the case where it did not.
fn shm_unlink(name: &str) {
    if let Ok(c_name) = std::ffi::CString::new(name) {
        // SAFETY: the name is one this process created, and unlinking a name that is already gone
        // is a harmless failure rather than undefined behaviour.
        unsafe { libc::shm_unlink(c_name.as_ptr()) };
    }
}

// --- the presenter -----------------------------------------------------------------------------

/// How the pixels travel.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Transport {
    /// A name in `/dev/shm`. 78 fps at a full pane, through tmux, measured.
    SharedMemory,
    /// The pixels down the pty. 8 fps at the same size, measured. See [`base64_escapes`].
    Base64,
}

/// Everything one browser surface needs to keep appearing in the pane.
///
/// The division of labour, because it is not obvious from the outside: the **pixels** are re-sent
/// every frame and the **placeholder text** is not. Placeholders are text the host application owns
/// and repaints by itself — that is the entire reason they are used — so they are written when the
/// geometry changes and when somebody says the screen was clobbered, and never per frame. A frame is
/// one `memcpy` and one short escape.
pub struct Painter {
    placement: Placement,
    style: Style,
    in_tmux: bool,
    place: Place,
    transport: Transport,
    /// The geometry the placeholder cells on the screen were written for, or `None` when there are
    /// none — after a clear, a resize, or a caller saying the host repainted over them.
    placed: Option<Placement>,
    sequence: u64,
    /// Shared memory names handed over and not yet taken back. See [`RETAINED_FRAMES`].
    handed_over: VecDeque<String>,
}

impl Painter {
    pub fn new(
        placement: Placement,
        in_tmux: bool,
        place: Place,
        transport: Transport,
    ) -> Painter {
        Painter {
            placement,
            style: Style::Explicit,
            in_tmux,
            place,
            transport,
            placed: None,
            sequence: 0,
            handed_over: VecDeque::new(),
        }
    }

    /// Which transport frames are travelling by at the moment — the one asked for until shared
    /// memory fails once, and [`Transport::Base64`] from then on. See [`Painter::paint`].
    pub fn transport(&self) -> Transport {
        self.transport
    }

    /// Say where the picture goes. Re-writes the placeholder cells on the next paint.
    pub fn set_placement(&mut self, placement: Placement) {
        if placement != self.placement {
            self.placement = placement;
            self.placed = None;
        }
    }

    /// Say that the host application drew over the placeholder cells, so they must be written again.
    ///
    /// **The one thing the presenter cannot notice for itself.** tmux repaints its own screen, so it
    /// keeps the placeholders alive without being asked — but a full-screen clear, an alternate
    /// screen switch or another program's output erases them like any other text, and from the
    /// inside that is indistinguishable from nothing having happened. Whoever owns the screen knows.
    pub fn invalidate_placement(&mut self) {
        self.placed = None;
    }

    /// One frame: the pixels, and the placeholder cells if they are not already on the screen.
    ///
    /// `rgb` is `width * height * 3` bytes, because the transmission says `f=24`. Anything shorter
    /// is refused rather than padded — the length is the only thing standing between a wrong number
    /// and a picture made of whatever was next in memory.
    ///
    /// **The pixels go first and the cells second.** Either order converges, but this one never
    /// shows a placeholder for an image that does not exist yet.
    ///
    /// This does not switch synchronised output (mode 2026) on and off around itself. The session
    /// owns the screen and does that; a presenter that emitted its own would fight whatever else is
    /// drawing in the same frame.
    pub fn paint(
        &mut self,
        out: &mut impl Write,
        rgb: &[u8],
        width: u32,
        height: u32,
    ) -> std::io::Result<()> {
        let expected = (width as usize)
            .checked_mul(height as usize)
            .and_then(|pixels| pixels.checked_mul(3))
            .ok_or_else(|| {
                std::io::Error::new(std::io::ErrorKind::InvalidInput, "impossible frame size")
            })?;
        if rgb.len() < expected {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                "the frame is shorter than the size it would be transmitted as",
            ));
        }
        let rgb = &rgb[..expected];

        // **The cursor move and the picture are one write, not two.** Between the move and the
        // escape there is a cursor sitting somewhere the session did not put it, and anything else
        // that draws in that gap draws in the wrong place. Bracketed with DECSC/DECRC so the
        // session's cursor comes back untouched.
        if self.place == Place::AtCursor {
            out.write_all(at_cursor_prologue(&self.placement).as_bytes())?;
        }
        if self.transport == Transport::SharedMemory
            && !self.send_shared_memory(out, rgb, width, height)?
        {
            // Shared memory is not a configuration, it is a thing that either worked or did not —
            // no `/dev/shm` at all, a full one, a sandbox. Falling back once and staying fallen back
            // beats discovering it again for every frame.
            self.transport = Transport::Base64;
        }
        if self.transport == Transport::Base64 {
            for escape in base64_escapes(&base64(rgb), &self.placement, width, height, self.place)
            {
                out.write_all(passthrough(&escape, self.in_tmux).as_bytes())?;
            }
        }
        if self.place == Place::AtCursor {
            out.write_all(AT_CURSOR_EPILOGUE.as_bytes())?;
        }

        // Placeholder cells are the other mechanism's half of the job; at the cursor there is
        // nothing to write and nothing that can be clobbered, because the picture is not standing
        // in for any text.
        if self.place == Place::Placeholders && self.placed != Some(self.placement) {
            match placeholder_block(&self.placement, self.style) {
                Some(block) => {
                    // Text, so **not** wrapped for passthrough: tmux is meant to read this.
                    out.write_all(block.as_bytes())?;
                    self.placed = Some(self.placement);
                }
                None => {
                    return Err(std::io::Error::new(
                        std::io::ErrorKind::InvalidInput,
                        "a placement larger than the diacritics can spell",
                    ));
                }
            }
        }
        out.flush()
    }

    /// `Ok(false)` when shared memory itself was unavailable, which is the caller's cue to fall
    /// back; a write error to the terminal is a real error and comes back as one.
    fn send_shared_memory(
        &mut self,
        out: &mut impl Write,
        rgb: &[u8],
        width: u32,
        height: u32,
    ) -> std::io::Result<bool> {
        self.sequence = self.sequence.wrapping_add(1);
        // The name has to be unique for as long as the object is: the pid keeps it out of another
        // bru's way, the counter out of the previous frames' — see `RETAINED_FRAMES`.
        let name = format!("/bru-{}-{}", std::process::id(), self.sequence);
        if shm_publish(&name, rgb).is_err() {
            return Ok(false);
        }
        let escape = shm_escape(&name, &self.placement, width, height, self.place);
        let result = out.write_all(passthrough(&escape, self.in_tmux).as_bytes());
        self.handed_over.push_back(name);
        while self.handed_over.len() > RETAINED_FRAMES {
            if let Some(old) = self.handed_over.pop_front() {
                shm_unlink(&old);
            }
        }
        result?;
        Ok(true)
    }

    /// Give the image back to the terminal and forget the cells.
    ///
    /// The placeholder characters themselves are not erased here — they are text in the host
    /// application's screen, and erasing text is the session's job. What this does is release the
    /// pixels kitty is storing, so that a browser that has stopped is not also a picture the
    /// terminal is still holding.
    pub fn clear(&mut self, out: &mut impl Write) -> std::io::Result<()> {
        let escape = delete_escape(self.placement.image_id);
        out.write_all(passthrough(&escape, self.in_tmux).as_bytes())?;
        self.placed = None;
        out.flush()
    }
}

impl Drop for Painter {
    /// Take back every name the terminal did not. Without this a browser that exits mid-frame
    /// leaves up to [`RETAINED_FRAMES`] frames — 12 MB at a full pane — in `/dev/shm` until reboot.
    fn drop(&mut self) {
        for name in self.handed_over.drain(..) {
            shm_unlink(&name);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The size is the encoding's ceiling, so it is asserted rather than trusted, and the table has
    /// to be strictly ascending or the binary search in [`diacritic_number`] is quietly wrong.
    #[test]
    fn the_table_is_the_right_size_and_in_order() {
        assert_eq!(ROWCOLUMN_DIACRITICS.len(), 297);
        assert_eq!(MAX_CELLS, 297);
        for pair in ROWCOLUMN_DIACRITICS.windows(2) {
            assert!(pair[0] < pair[1], "{:?} is not before {:?}", pair[0], pair[1]);
        }
    }

    /// **The known values, from kitty's own documentation rather than from the table this checks.**
    /// The protocol page states in prose that U+305 is 0, U+30D is 1 and U+30E is 2; the rest of
    /// these are the next entries of the file the table was copied from.
    #[test]
    fn the_diacritics_spell_the_numbers_kitty_documents() {
        assert_eq!(diacritic(0), Some('\u{305}'));
        assert_eq!(diacritic(1), Some('\u{30d}'));
        assert_eq!(diacritic(2), Some('\u{30e}'));
        assert_eq!(diacritic(3), Some('\u{310}'));
        assert_eq!(diacritic(4), Some('\u{312}'));
        assert_eq!(diacritic(296), Some('\u{1d244}'));
        assert_eq!(diacritic(297), None, "past the end is a refusal, not a wrap");
    }

    /// Every number the encoding can spell, both ways. A table copied by hand is only as good as
    /// the round trip over the whole of it.
    #[test]
    fn every_diacritic_reads_back_as_the_number_it_spells() {
        for n in 0..MAX_CELLS {
            let ch = diacritic(n).expect("in range");
            assert_eq!(diacritic_number(ch), Some(n));
        }
        assert_eq!(diacritic_number('a'), None);
        assert_eq!(diacritic_number(PLACEHOLDER), None);
    }

    /// The id in the cell's colour: a palette index while it fits in one, true colour after that.
    #[test]
    fn an_image_id_that_fits_in_a_byte_travels_as_a_palette_index() {
        assert_eq!(foreground_for_id(42), "\x1b[38;5;42m");
        assert_eq!(foreground_for_id(IMAGE_ID_VIEW), "\x1b[38;5;190m");
        // Above a byte there is nothing else to use, quantising tmux or not.
        assert_eq!(foreground_for_id(0x01_0203), "\x1b[38;2;1;2;3m");
        // The top byte is never in the colour — it is a third diacritic.
        assert_eq!(foreground_for_id(42 + (2 << 24)), "\x1b[38;5;42m");
        assert_eq!(most_significant_byte_diacritic(42 + (2 << 24)), Some('\u{30e}'));
        assert_eq!(most_significant_byte_diacritic(42), None);
    }

    /// **kitty's own documented example, byte for byte.** The protocol page prints a 2x2 placeholder
    /// for image id 42 as these two `printf` lines, and if this module's output differs from them
    /// the picture is somewhere else or is not drawn at all.
    ///
    /// ```text
    /// printf "\e[38;5;42m\U10EEEE\U0305\U0305\U10EEEE\U0305\U030D\e[39m\n"
    /// printf "\e[38;5;42m\U10EEEE\U030D\U0305\U10EEEE\U030D\U030D\e[39m\n"
    /// ```
    #[test]
    fn a_row_of_placeholders_is_what_the_protocol_documents() {
        let placement = Placement::new(42, 1, 1, 2, 2);
        assert_eq!(
            placeholder_row(&placement, 0, Style::Explicit).unwrap(),
            "\x1b[38;5;42m\u{10eeee}\u{305}\u{305}\u{10eeee}\u{305}\u{30d}\x1b[39m"
        );
        assert_eq!(
            placeholder_row(&placement, 1, Style::Explicit).unwrap(),
            "\x1b[38;5;42m\u{10eeee}\u{30d}\u{305}\u{10eeee}\u{30d}\u{30d}\x1b[39m"
        );
    }

    /// The same page's example for an id whose top byte is not zero: 33554474 = 42 + (2 << 24), so
    /// the colour still says 42 and every cell carries a third diacritic saying 2.
    #[test]
    fn the_top_byte_of_the_id_is_a_third_diacritic_on_every_cell() {
        let placement = Placement::new(42 + (2 << 24), 1, 1, 2, 2);
        assert_eq!(
            placeholder_row(&placement, 0, Style::Explicit).unwrap(),
            "\x1b[38;5;42m\u{10eeee}\u{305}\u{305}\u{30e}\u{10eeee}\u{305}\u{30d}\u{30e}\x1b[39m"
        );
    }

    /// The short form, also from the documentation: the row on the first cell only, everything
    /// after it inheriting. Not the default — see [`Style`].
    #[test]
    fn the_compact_form_leaves_the_column_to_be_inherited() {
        let placement = Placement::new(42, 1, 1, 2, 3);
        assert_eq!(
            placeholder_row(&placement, 0, Style::Compact).unwrap(),
            "\x1b[38;5;42m\u{10eeee}\u{305}\u{10eeee}\u{10eeee}\x1b[39m"
        );
        assert_eq!(
            placeholder_row(&placement, 1, Style::Compact).unwrap(),
            "\x1b[38;5;42m\u{10eeee}\u{30d}\u{10eeee}\u{10eeee}\x1b[39m"
        );
    }

    /// Each row is positioned by `CSI row;col H` — 1-based, and the block saves and restores the
    /// cursor around itself because it is drawing in somebody else's screen.
    ///
    /// **And there is no newline anywhere in it.** A newline written after the bottom-right cell
    /// scrolls the pane and takes the picture with it.
    #[test]
    fn a_block_positions_every_row_and_never_ends_a_line() {
        let placement = Placement::new(42, 5, 3, 2, 1);
        let block = placeholder_block(&placement, Style::Explicit).unwrap();
        assert!(block.starts_with("\x1b7"), "the cursor is saved first");
        assert!(block.ends_with("\x1b8"), "and put back last");
        assert!(block.contains("\x1b[5;3H"), "the first row is where it was asked for");
        assert!(block.contains("\x1b[6;3H"), "and the second is one line under it");
        assert!(!block.contains('\n'), "a newline here scrolls the pane");
        assert!(!block.contains('\r'));
    }

    /// A geometry the diacritics cannot spell is refused, and refused the same way twice: by the
    /// question and by the attempt.
    #[test]
    fn a_placement_bigger_than_the_encoding_is_refused() {
        let too_wide = Placement::new(42, 1, 1, 1, 298);
        assert!(!too_wide.is_encodable());
        assert_eq!(placeholder_block(&too_wide, Style::Explicit), None);
        let empty = Placement::new(42, 1, 1, 0, 4);
        assert!(!empty.is_encodable());
        assert_eq!(placeholder_block(&empty, Style::Explicit), None);
        assert!(Placement::new(42, 1, 1, 297, 297).is_encodable());
    }

    #[test]
    fn base64_matches_the_examples_from_rfc_4648() {
        assert_eq!(base64(b""), "");
        assert_eq!(base64(b"f"), "Zg==");
        assert_eq!(base64(b"fo"), "Zm8=");
        assert_eq!(base64(b"foo"), "Zm9v");
        assert_eq!(base64(b"foob"), "Zm9vYg==");
        assert_eq!(base64(b"fooba"), "Zm9vYmE=");
        assert_eq!(base64(b"foobar"), "Zm9vYmFy");
    }

    /// Every escape byte doubled, wrapped in the DCS, terminated. Getting this wrong does not fail
    /// loudly — tmux eats the sequence and nothing is drawn, which reads as a terminal with no
    /// graphics support.
    #[test]
    fn the_tmux_wrapper_doubles_every_escape() {
        let payload = "\x1b_Ga=T;AAAA\x1b\\";
        assert_eq!(passthrough(payload, false), payload, "outside tmux nothing is added");
        let wrapped = passthrough(payload, true);
        assert!(wrapped.starts_with("\x1bPtmux;\x1b\x1b_Ga=T;AAAA"));
        assert!(wrapped.ends_with("\x1b\x1b\\\x1b\\"));
        assert_eq!(
            wrapped.matches('\x1b').count(),
            payload.matches('\x1b').count() * 2 + 2,
            "the payload's escapes are doubled and the wrapper adds two of its own"
        );
    }

    /// The shared memory transmission carries a name and not pixels, asks for silence, and creates
    /// a virtual placement rather than drawing anything.
    #[test]
    fn the_shared_memory_escape_sends_the_name_and_asks_for_no_answer() {
        let placement = Placement::new(190, 1, 1, 40, 100);
        let escape = shm_escape("/bru-7-1", &placement, 990, 1350, Place::Placeholders);
        assert_eq!(
            escape,
            format!(
                "\x1b_Ga=T,U=1,q=2,i=190,p=1,f=24,s=990,v=1350,c=100,r=40,t=s;{}\x1b\\",
                base64(b"/bru-7-1")
            )
        );
    }

    /// Chunking: the geometry rides on the first escape only, the rest carry `m` and the quiet flag,
    /// and the last one says there is no more.
    #[test]
    fn base64_frames_are_chunked_with_the_geometry_on_the_first_one_only() {
        let placement = Placement::new(190, 1, 1, 2, 2);
        assert!(base64_escapes("", &placement, 1, 1, Place::Placeholders).is_empty());

        let encoded = "A".repeat(CHUNK + 1);
        let escapes = base64_escapes(&encoded, &placement, 4, 4, Place::Placeholders);
        assert_eq!(escapes.len(), 2);
        assert!(escapes[0].starts_with("\x1b_Ga=T,U=1,q=2,i=190,p=1,f=24,s=4,v=4,c=2,r=2,m=1;"));
        assert_eq!(escapes[1], "\x1b_Gq=2,m=0;A\x1b\\");
        // Every byte of the payload goes out exactly once.
        let sent: String = escapes
            .iter()
            .map(|escape| {
                let body = escape.split_once(';').expect("a payload").1;
                body.trim_end_matches("\x1b\\").to_string()
            })
            .collect();
        assert_eq!(sent, encoded);
    }

    /// Deleting frees the pixels rather than only forgetting where they were, and says nothing.
    #[test]
    fn deleting_releases_the_stored_image() {
        assert_eq!(delete_escape(190), "\x1b_Ga=d,d=I,i=190,q=2\x1b\\");
    }

    /// Rounding down, because a placement one cell too tall pushes the pane into scrolling.
    #[test]
    fn a_picture_covers_only_the_cells_it_fills() {
        assert_eq!(cells_for(990, 1350, 10, 20), Some((67, 99)));
        assert_eq!(cells_for(995, 1359, 10, 20), Some((67, 99)), "the remainder is not a cell");
        assert_eq!(cells_for(990, 1350, 0, 20), None);
        assert_eq!(cells_for(5, 1350, 10, 20), None, "narrower than one cell is no placement");
    }

    /// The union, clipped to the frame, and `None` for a frame nothing changed in.
    #[test]
    fn damage_is_one_rectangle_clipped_to_the_frame() {
        let rects = [
            Rect { x: 10, y: 20, width: 5, height: 5 },
            Rect { x: 100, y: 0, width: 10, height: 10 },
        ];
        assert_eq!(
            damage_bounds(&rects, 800, 600),
            Some(Rect { x: 10, y: 0, width: 100, height: 25 })
        );
        assert_eq!(damage_bounds(&[], 800, 600), None);
        // Empty and negative rectangles say nothing changed rather than describing a nowhere.
        let nothing = [
            Rect { x: 0, y: 0, width: 0, height: 10 },
            Rect { x: -50, y: -50, width: 10, height: 10 },
        ];
        assert_eq!(damage_bounds(&nothing, 800, 600), None);
        // A rectangle reaching past the frame is cut to it, not believed.
        let overrun = [Rect { x: 790, y: 590, width: 100, height: 100 }];
        assert_eq!(
            damage_bounds(&overrun, 800, 600),
            Some(Rect { x: 790, y: 590, width: 10, height: 10 })
        );
    }

    /// A frame shorter than the size it would be transmitted as is refused, because the length is
    /// the only thing between a wrong number and a picture made of whatever was next in memory.
    #[test]
    fn a_short_frame_is_refused_rather_than_read_past() {
        let mut painter = Painter::new(Placement::new(190, 1, 1, 2, 2), false, Place::Placeholders, Transport::SharedMemory);
        let mut out = Vec::new();
        let error = painter.paint(&mut out, &[0u8; 11], 2, 2).expect_err("4 pixels need 12 bytes");
        assert_eq!(error.kind(), std::io::ErrorKind::InvalidInput);
        assert!(out.is_empty(), "nothing is written for a frame that was not accepted");
    }

    /// The division of labour: pixels every frame, placeholder cells only when the geometry moved.
    ///
    /// **The distinction the black pane turned on.** `OK` is a yes, anything else is a no, and
    /// nothing at all is neither — the three have to stay three.
    #[test]
    fn the_transport_question_can_be_answered_no() {
        assert_eq!(shm_query_answer(b"\x1b_Gi=189;OK\x1b\\"), Some(true));
        assert_eq!(shm_query_answer(b"\x1b_Gi=189;ENOENT:No such file\x1b\\"), Some(false));
        assert_eq!(shm_query_answer(b"\x1b_Gi=189;EBADF:bad medium\x1b\\"), Some(false));
        assert_eq!(shm_query_answer(b""), None, "silence is not a refusal");
        assert_eq!(shm_query_answer(b"\x1b_Gi=190;OK\x1b\\"), None, "another image's answer");
        // The reply can arrive behind whatever else the terminal was saying.
        assert_eq!(shm_query_answer(b"\x1b[0n\x1b_Gi=189;OK\x1b\\"), Some(true));
    }

    /// The question transmits nothing and displays nothing — `a=q` is the whole point, because
    /// asking must not put a picture on a screen the caller has not finished setting up.
    #[test]
    fn the_transport_question_only_asks() {
        let escape = shm_query_escape("/bru-probe-7", false);
        assert_eq!(
            escape,
            format!("\x1b_Gi=189,a=q,t=s,f=24,s=1,v=1;{}\x1b\\", base64(b"/bru-probe-7"))
        );
        assert!(!escape.contains("a=T"), "a query, never a display");
        // …and under tmux it has to go around tmux like every other graphics escape.
        assert!(shm_query_escape("/bru-probe-7", true).starts_with("\x1bPtmux;"));
    }

    /// **The zellij case, in a test.** The escape must say `C=1` and must not say `U=1`, because a
    /// host that ignores placeholders draws a picture from the first and nothing at all from the
    /// second — and acknowledges both.
    #[test]
    fn placing_at_the_cursor_asks_for_a_picture_and_not_for_cells() {
        let placement = Placement::new(190, 7, 3, 40, 100);
        let escape = shm_escape("/bru-7-1", &placement, 990, 1350, Place::AtCursor);
        assert_eq!(
            escape,
            format!(
                "\x1b_Ga=T,C=1,q=2,i=190,p=1,f=24,s=990,v=1350,c=100,r=40,t=s;{}\x1b\\",
                base64(b"/bru-7-1")
            )
        );
        assert!(!escape.contains("U=1"), "a placeholder key here is the bug this exists for");
    }

    /// The cursor is the session's. It is moved to the rectangle, the picture is drawn, and it goes
    /// back — and no placeholder cell is ever written, because nothing is standing in for text.
    #[test]
    fn the_cursor_is_borrowed_for_the_picture_and_given_back() {
        let mut painter = Painter::new(Placement::new(42, 7, 3, 1, 1), false, Place::AtCursor, Transport::Base64);
        let frame = [0u8; 3];

        let mut out = Vec::new();
        painter.paint(&mut out, &frame, 1, 1).expect("a frame");
        let out = String::from_utf8(out).expect("utf-8");
        assert!(out.starts_with("\x1b7\x1b[7;3H"), "saved, then moved to the rectangle");
        assert!(out.ends_with("\x1b8"), "and put back");
        assert!(out.contains("\x1b_Ga=T,C=1,q=2,i=42"), "the pixels, in between");
        assert!(!out.contains(PLACEHOLDER), "no cells at the cursor, ever");

        // And the second frame is the same, where the placeholder path would have gone quiet.
        let mut second = Vec::new();
        painter.paint(&mut second, &frame, 1, 1).expect("a frame");
        let second = String::from_utf8(second).expect("utf-8");
        assert!(second.starts_with("\x1b7\x1b[7;3H") && second.ends_with("\x1b8"));
    }

    /// **tmux is answered before zellij and that ordering is the content of the function.** Under
    /// tmux the escape goes around tmux to a terminal whose cursor tmux owns, so "at the cursor"
    /// names a position nobody agrees on; placeholders are what that case has.
    #[test]
    fn the_host_chooses_the_mechanism() {
        assert_eq!(place_for(false, false), Place::Placeholders, "plain kitty, as before");
        assert_eq!(place_for(true, false), Place::Placeholders, "tmux");
        assert_eq!(place_for(false, true), Place::AtCursor, "zellij");
        assert_eq!(place_for(true, true), Place::Placeholders, "tmux inside zellij is still tmux");
    }

    /// The transport is forced to base64 here so the test needs no `/dev/shm` and no terminal.
    #[test]
    fn the_placeholder_cells_are_written_once_and_the_pixels_every_time() {
        let mut painter = Painter::new(Placement::new(42, 1, 1, 1, 1), false, Place::Placeholders, Transport::Base64);
        let frame = [0u8; 3];

        let mut first = Vec::new();
        painter.paint(&mut first, &frame, 1, 1).expect("a frame");
        let first = String::from_utf8(first).expect("utf-8");
        assert!(first.contains("\x1b_Ga=T,U=1,q=2,i=42"), "the pixels");
        assert!(first.contains(PLACEHOLDER), "and the cells");

        let mut second = Vec::new();
        painter.paint(&mut second, &frame, 1, 1).expect("a frame");
        let second = String::from_utf8(second).expect("utf-8");
        assert!(second.contains("\x1b_Ga=T,U=1,q=2,i=42"), "the pixels again");
        assert!(!second.contains(PLACEHOLDER), "the cells are the host application's now");

        // …until somebody says the screen was drawn over.
        painter.invalidate_placement();
        let mut third = Vec::new();
        painter.paint(&mut third, &frame, 1, 1).expect("a frame");
        assert!(String::from_utf8(third).expect("utf-8").contains(PLACEHOLDER));
    }

    /// Moving the picture re-writes the cells; setting the same placement twice does not.
    #[test]
    fn moving_the_picture_writes_the_cells_again() {
        let mut painter = Painter::new(Placement::new(42, 1, 1, 1, 1), false, Place::Placeholders, Transport::Base64);
        let frame = [0u8; 3];
        let mut sink = Vec::new();
        painter.paint(&mut sink, &frame, 1, 1).expect("a frame");
        assert_eq!(painter.placed, Some(painter.placement));

        painter.set_placement(Placement::new(42, 1, 1, 1, 1));
        assert_eq!(painter.placed, Some(painter.placement), "the same place is not a move");
        painter.set_placement(Placement::new(42, 2, 1, 1, 1));
        assert_eq!(painter.placed, None, "a different one is");
    }

    /// The pane is not the only thing in the terminal: what is transmitted must be given back.
    #[test]
    fn clearing_frees_the_image_the_terminal_is_holding() {
        let mut painter = Painter::new(Placement::new(42, 1, 1, 1, 1), true, Place::Placeholders, Transport::SharedMemory);
        let mut out = Vec::new();
        painter.clear(&mut out).expect("a write to a Vec");
        let out = String::from_utf8(out).expect("utf-8");
        assert!(out.starts_with("\x1bPtmux;"), "a graphics escape goes around tmux, not through it");
        assert!(out.contains("a=d,d=I,i=42"));
        assert_eq!(painter.placed, None);
    }

    /// A shared memory object written and read back, which is the one thing here that needs a
    /// kernel rather than a terminal.
    #[test]
    fn a_frame_survives_the_trip_through_dev_shm() {
        let name = format!("/bru-test-{}-{}", std::process::id(), line!());
        let pixels: Vec<u8> = (0..=255u8).cycle().take(4096).collect();
        if shm_publish(&name, &pixels).is_err() {
            // A machine with no shared memory is exactly the case `Transport::Base64` exists for,
            // and is not a reason for the test suite to fail.
            return;
        }
        let path = std::path::Path::new("/dev/shm").join(name.trim_start_matches('/'));
        let read = std::fs::read(&path).expect("the object this test just created");
        shm_unlink(&name);
        assert_eq!(read, pixels);
        assert!(!path.exists(), "and the name is taken back");
        // Creating it a second time under the same name must not silently reuse somebody's object.
        shm_publish(&name, &pixels).expect("a fresh name");
        assert!(shm_publish(&name, &pixels).is_err(), "O_EXCL, so the second one fails");
        shm_unlink(&name);
    }
}
